name: CI

on: 
  push:
      
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure PHP 8.3
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, zip, sqlite3
  
      - name: Install composer dependencies
        run: composer install
      
      - name: Run tests
        run: vendor/bin/pest --compact